ProceduresRecord.Web.MVC/Controllers/PeopleController.cs
using System;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using ProceduresRecord.Web.MVC.Contexts;
using ProceduresRecord.Web.MVC.Models;
using System.Web.UI.WebControls;
using System.Reflection;
using System.ComponentModel;
using System.Collections.Generic;
using ProceduresRecord.Web.MVC.Helpers;
using ProceduresRecord.Web.MVC.Authorizations;

namespace ProceduresRecord.Web.MVC.Controllers
{
    [AuthorizationFilter]
    [CommanderAllowsProgram]
    public class PeopleController : Controller
    {
        public Context db { get; set; } = new Context();
        private object PeopleLocker { get; set; } = new object();

        #region Index

        // GET: People
        public ActionResult Index()
        {
            populateViewBagWithPeopleSearchOptions();
            return View(db.People.ToList());
        }

        private void populateViewBagWithPeopleSearchOptions()
        {
            Array optionsFromEnum = Enum.GetValues(typeof(PeopleSearchOptions));
            var searchOptions = from PeopleSearchOptions option in optionsFromEnum
                                select new
                                {
                                    ID = (int)option,
                                    Name = getOptionDescription(option)
                                };
            ViewBag.SearchOptions = new SelectList(searchOptions, "ID", "Name");
        }

        private object getOptionDescription(Enum value)
        {
            FieldInfo field = value.GetType().GetField(value.ToString());
            DescriptionAttribute[] attributes =
                (DescriptionAttribute[])field.GetCustomAttributes(
                    typeof(DescriptionAttribute), false);

            if (attributes.Length > 0)
            {
                return attributes[0].Description;
            }
            else
            {
                return value.ToString();
            }
        }

        // POST: People
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(PeopleSearchOptions searchOptions, string searchValue)
        {
            populateViewBagWithPeopleSearchOptions();
            return filterPeople(searchOptions, searchValue);
        }

        private ActionResult filterPeople(PeopleSearchOptions searchOptions,
            string searchValue)
        {
            string preparedSearchValue = GenericFunctions.ToLowerAndRemoveDiacritics(searchValue);
            return filterBasedOnSearchOption(searchOptions, preparedSearchValue);
        }

        private ActionResult filterBasedOnSearchOption(PeopleSearchOptions searchOptions,
            string preparedSearchValue)
        {
            List<Person> wantedPeople;
            switch (searchOptions)
            {
                case PeopleSearchOptions.NombresYApellidos:
                    wantedPeople = filterBasedOnNamesAndSurnames(preparedSearchValue);
                    return View(wantedPeople);
                case PeopleSearchOptions.NumeroDeExpediente:
                    wantedPeople = filterBasedOnRecordNumber(preparedSearchValue);
                    return View(wantedPeople);
                case PeopleSearchOptions.AñoDeExpediente:
                    wantedPeople = filterBasedOnRecordYear(preparedSearchValue);
                    return View(wantedPeople);
                case PeopleSearchOptions.FechaDeNacimiento:
                    wantedPeople = filterBasedOnBirthDate(preparedSearchValue);
                    return View(wantedPeople);
                case PeopleSearchOptions.Nacionalidad:
                    wantedPeople = filterBasedOnNationality(preparedSearchValue);
                    return View(wantedPeople);
                default:
                    Response.Write("<script>alert('Opción inválida en las opciones de búsqueda de Personas.');</script>");
                    wantedPeople = db.People.ToList();
                    return View(wantedPeople);
            }
        }

        private List<Person> filterBasedOnNamesAndSurnames(string preparedNamesAndSurnames)
        {
            string[] searchedWords = preparedNamesAndSurnames.Split(null);
            List<Person> wantedPeople = new List<Person>();
            List<Person> allPeopleInDB = db.People.ToList();
            foreach (var person in allPeopleInDB)
            {
                string preparedPersonNames = GenericFunctions.ToLowerAndRemoveDiacritics(person.Names);
                string preparedPersonSurnames = GenericFunctions.ToLowerAndRemoveDiacritics(person.Surnames);
                bool hasAllWords = true;
                for (int i = 0; i < searchedWords.Length && hasAllWords; i++)
                {
                    string word = searchedWords[i];
                    if (!preparedPersonNames.Contains(word) &&
                        !preparedPersonSurnames.Contains(word))
                        hasAllWords = false;
                }
                if (hasAllWords)
                    wantedPeople.Add(person);
            }
            return wantedPeople;
        }

        private List<Person> filterBasedOnRecordNumber(string recordNumberAsString)
        {
            if (string.IsNullOrWhiteSpace(recordNumberAsString))
                return db.People.ToList();
            int wantedRecordNumber = int.Parse(recordNumberAsString);
            return db.People.Where(p => p.RecordNumber == wantedRecordNumber).ToList();
        }

        private List<Person> filterBasedOnRecordYear(string recordYearAsString)
        {
            if (string.IsNullOrWhiteSpace(recordYearAsString))
                return db.People.ToList();
            int wantedRecordYear = int.Parse(recordYearAsString);
            return db.People.Where(p => p.RecordYear == wantedRecordYear).ToList();
        }

        private List<Person> filterBasedOnBirthDate(string birthDateAsString)
        {
            if (string.IsNullOrWhiteSpace(birthDateAsString))
                return db.People.ToList();
            DateTime wantedBirthDate = DateTime.Parse(birthDateAsString);
            return db.People.Where(p => p.BirthDate == wantedBirthDate).ToList();
        }

        private List<Person> filterBasedOnNationality(string preparedSearchValue)
        {
            if (string.IsNullOrWhiteSpace(preparedSearchValue))
                return db.People.ToList();
            return db.People
                .Where(p => p.Nationality.Name.ToLower() == preparedSearchValue)
                .ToList();
        }

        #endregion

        // GET: People/Create
        [AuthorizationFilter(Profiles.Administrador, Profiles.Avanzado)]
        public ActionResult Create()
        {
            populateViewBagWithCountries();
            return View();
        }

        private void populateViewBagWithCountries()
        {
            ViewBag.Countries = new SelectList(db.Countries, "Id", "Name");
        }

        // POST: People/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AuthorizationFilter(Profiles.Administrador, Profiles.Avanzado)]
        public ActionResult Create([Bind(Include = "RecordNumber,RecordYear,Surnames,Names,BirthDate,MinisterialResolution,CheckNumber,RollNumber,NationalityId,BirthPlaceId")] Person person)
        {
            lock (PeopleLocker)
            {
                if (ModelState.IsValid)
                {
                    db.People.Add(person);
                    db.SaveChanges();
                    LogHelper.LogAction("Alta de Persona: " + person.Names + " " + person.Surnames);
                    return RedirectToAction("Index");
                }
            }
            populateViewBagWithCountries();
            return View(person);
        }

        // GET: People/Edit/5
        [AuthorizationFilter(Profiles.Administrador, Profiles.Avanzado)]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Person person = db.People.Find(id);
            if (person == null)
            {
                return HttpNotFound();
            }
            populateViewBagWithCountries();
            return View(person);
        }

        // POST: People/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AuthorizationFilter(Profiles.Administrador, Profiles.Avanzado)]
        public ActionResult Edit([Bind(Include = "Id,RecordNumber,RecordYear,Surnames,Names,BirthDate,MinisterialResolution,CheckNumber,RollNumber,NationalityId,BirthPlaceId")] Person person)
        {
            lock (PeopleLocker)
            {
                if (ModelState.IsValid)
                {
                    bool personExists = db.People.Any(p => p.Id == person.Id);
                    if (!personExists)
                    {
                        return HttpNotFound();
                    }
                    db.Entry(person).State = EntityState.Modified;
                    db.SaveChanges();
                    LogHelper.LogAction("Modificación de Persona: " + person.Names + " " + person.Surnames);
                    return RedirectToAction("Index");
                }
            }
            populateViewBagWithCountries();
            return View(person);
        }

        // GET: People/Delete/5
        [AuthorizationFilter(Profiles.Administrador, Profiles.Avanzado)]
        public ActionResult Delete(int? id)
        {
            if (id == null)

ProceduresRecord.Web.MVC/Controllers/ProceduresController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using ProceduresRecord.Web.MVC.Contexts;
using ProceduresRecord.Web.MVC.Models;
using System.Collections.Generic;
using ProceduresRecord.Web.MVC.Authorizations;
using ProceduresRecord.Web.MVC.Helpers;

namespace ProceduresRecord.Web.MVC.Controllers
{
    [AuthorizationFilter]
    [CommanderAllowsProgram]
    public class ProceduresController : Controller
    {
        public Context db { get; set; } = new Context();
        private object ProceduresLocker { get; set; } = new object();

        // GET: Procedures
        public ActionResult Index(int? personId)
        {
            if (personId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ViewBag.PersonId = (int)personId;
            return View(getPersonProcedures((int)personId));
        }

        private List<Procedure> getPersonProcedures(int personId)
        {
            return db.Procedures.Where(p => p.PersonId == personId).ToList();
        }

        // GET: Procedures/Create
        [AuthorizationFilter(Profiles.Administrador, Profiles.Avanzado)]
        public ActionResult Create(int? personId)
        {
            if (personId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Procedure procedure = new Procedure { PersonId = (int)personId };
            return View(procedure);
        }

        // POST: Procedures/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AuthorizationFilter(Profiles.Administrador, Profiles.Avanzado)]
        public ActionResult Create([Bind(Include = "Date,Description,PersonId")] Procedure procedure)
        {
            lock (ProceduresLocker)
            {
                if (ModelState.IsValid)
                {
                    db.Procedures.Add(procedure);
                    db.SaveChanges();
                    LogHelper.LogAction("Alta de Trámite: " + procedure.Description);
                    return RedirectToAction("Index", new { personId = procedure.PersonId });
                } 
            }
            return View(procedure);
        }

        // GET: Procedures/Edit/5
        [AuthorizationFilter(Profiles.Administrador, Profiles.Avanzado)]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Procedure procedure = db.Procedures.Find(id);
            if (procedure == null)
            {
                return HttpNotFound();
            }
            return View(procedure);
        }

        // POST: Procedures/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AuthorizationFilter(Profiles.Administrador, Profiles.Avanzado)]
        public ActionResult Edit([Bind(Include = "Id,Date,Description,PersonId")] Procedure procedure)
        {
            lock (ProceduresLocker)
            {
                if (ModelState.IsValid)
                {
                    bool procedureExists = db.Procedures.Any(p => p.Id == procedure.Id);
                    if (!procedureExists)
                    {
                        return HttpNotFound();
                    }
                    db.Entry(procedure).State = EntityState.Modified;
                    db.SaveChanges();
                    LogHelper.LogAction("Modificación de Trámite: " + procedure.Description);
                    return RedirectToAction("Index", new { personId = procedure.PersonId });
                } 
            }
            return View(procedure);
        }

        // GET: Procedures/Delete/5
        [AuthorizationFilter(Profiles.Administrador, Profiles.Avanzado)]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Procedure procedure = db.Procedures.Find(id);
            if (procedure == null)
            {
                return HttpNotFound();
            }
            return View(procedure);
        }

        // POST: Procedures/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [AuthorizationFilter(Profiles.Administrador, Profiles.Avanzado)]
        public ActionResult DeleteConfirmed(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Procedure procedure;
            lock (ProceduresLocker)
            {
                procedure = db.Procedures.Find(id);
                if (procedure == null)
                {
                    return HttpNotFound();
                }
                db.Procedures.Remove(procedure);
                db.SaveChanges();
                LogHelper.LogAction("Baja de Trámite: " + procedure.Description);
            }
            return RedirectToAction("Index", new { personId = procedure.PersonId });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProceduresRecord.Web.MVC/Views/People/Create.cshtml
@model ProceduresRecord.Web.MVC.Models.Person

@{
    ViewBag.Title = "Crear Persona";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Names, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Names, new { htmlAttributes = new { @class = "form-control", @maxlength = "30" } })
                @Html.ValidationMessageFor(model => model.Names, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Surnames, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Surnames, new { htmlAttributes = new { @class = "form-control", @maxlength = "40" } })
                @Html.ValidationMessageFor(model => model.Surnames, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RecordNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RecordNumber, new { htmlAttributes = new { @class = "form-control", @max = "9999" } })
                @Html.ValidationMessageFor(model => model.RecordNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RecordYear, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RecordYear, new { htmlAttributes = new { @class = "form-control", @max = "9999" } })
                @Html.ValidationMessageFor(model => model.RecordYear, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NationalityId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.NationalityId, (IEnumerable<SelectListItem>)ViewBag.Countries, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.NationalityId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BirthPlaceId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.BirthPlaceId, (IEnumerable<SelectListItem>)ViewBag.Countries, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.BirthPlaceId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BirthDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BirthDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BirthDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MinisterialResolution, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MinisterialResolution, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MinisterialResolution, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CheckNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CheckNumber, new { htmlAttributes = new { @class = "form-control", @max = "9999" } })
                @Html.ValidationMessageFor(model => model.CheckNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RollNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RollNumber, new { htmlAttributes = new { @class = "form-control", @maxlength = "40" } })
                @Html.ValidationMessageFor(model => model.RollNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Confirmar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver a la Lista", "Index")
</div>

ProceduresRecord.Web.MVC/Views/People/Delete.cshtml
@model ProceduresRecord.Web.MVC.Models.Person

@{
    ViewBag.Title = "Eliminar Persona";
}

<h2>@ViewBag.Title</h2>

<div>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.Names)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Names)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Surnames)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Surnames)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RecordNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RecordNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RecordYear)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RecordYear)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BirthPlace)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BirthPlace.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nationality)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nationality.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BirthDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MinisterialResolution)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MinisterialResolution)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CheckNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CheckNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RollNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RollNumber)
        </dd>

    </dl>

    @* Remember: Html.BeginForm gets the id from the URI, so no need to use a hidden id field *@
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <b>Nota: Si elimina esta persona, sus trámites se eliminarán automáticamente</b>

        <br>
        <br>

        <div class="form-actions no-color">
            <input type="submit" value="Confirmar" class="btn btn-default" /> |
            @Html.ActionLink("Volver a la Lista", "Index")
        </div>
    }
</div>

ProceduresRecord.Web.MVC/Views/People/Index.cshtml
@model IEnumerable<ProceduresRecord.Web.MVC.Models.Person>
@using ProceduresRecord.Web.MVC.Models
@{User loggedUser = (User)Session["user"];}

@{
    ViewBag.Title = "Personas";
}

<h2>@ViewBag.Title</h2>

@if (loggedUser.Profile != Profiles.Básico)
{
    <p>
        @Html.ActionLink("Crear", "Create")
    </p>
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="col-xs-8 col-xs-offset-2">
        <div class="input-group">
            @Html.DropDownList("SearchOptions", (IEnumerable<SelectListItem>)ViewBag.SearchOptions, new { @id = "searchOptions", @class = "selectpicker" })
            @Html.TextBox("SearchValue", null, new { @id = "inputPeopleSearch", @class = "form-control hundred-Per-Cent-Max-Width", @placeholder = "Buscar...", @type = "text" })
            <span class="input-group-btn">
                <button class="btn btn-default" type="submit"><span class="glyphicon glyphicon-search"></span></button>
            </span>
        </div>
    </div>
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Names)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Surnames)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RecordNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RecordYear)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nationality)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BirthPlace)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BirthDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MinisterialResolution)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CheckNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RollNumber)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Names)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Surnames)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RecordNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RecordYear)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nationality.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BirthPlace.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BirthDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MinisterialResolution)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CheckNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RollNumber)
            </td>
            <td>
                @if (loggedUser.Profile != Profiles.Básico)
                {
                    @Html.ActionLink("Editar", "Edit", new { id = item.Id }) <text>|</text>
                    @Html.ActionLink("Eliminar", "Delete", new { id = item.Id }) <text>|</text>
                }
                @Html.ActionLink("Trámites", "Index", "Procedures", new { personId = item.Id }, "")
            </td>
        </tr>
    }

</table>

<!-- Javascript Documents .js -->
<script type="text/javascript" src="~/Scripts/People/searchOptions.js"></script>