ProceduresRecord.Web.MVC/Controllers/CommanderController.cs
using ProceduresRecord.Web.MVC.Authorizations;
using ProceduresRecord.Web.MVC.Contexts;
using System.Web.Mvc;
using System;
using System.Collections.Generic;
using ProceduresRecord.Web.MVC.Helpers;
using ProceduresRecord.Web.MVC.Services;

namespace ProceduresRecord.Web.MVC.Controllers
{
    [CommanderAuthorization]
    public class CommanderController : Controller
    {
        public Context db { get; set; } = new Context();

        //GET
        public ActionResult DeleteDataBase()
        {
            return View();
        }
        
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteDataBaseConfirmed()
        {
            db.Database.Delete();
            return RedirectToAction("Index", "Home");
        }

        //Get
        public ActionResult ProgramParameters()
        {
            populateViewBagWithProgramParameters();
            return View();
        }

        private void populateViewBagWithProgramParameters()
        {
            List<SelectListItem> programEnabledOptions = new List<SelectListItem>();
            programEnabledOptions.Add(new SelectListItem
            {
                Text = "Si",
                Value = "true",
                Selected = CommanderVariablesService.GetProgramIsAuthorized()
            });
            programEnabledOptions.Add(new SelectListItem
            {
                Text = "No",
                Value = "false",
                Selected = !CommanderVariablesService.GetProgramIsAuthorized()
            });
            ViewBag.ProgramEnabled = programEnabledOptions;

            ViewBag.ProgramDisabledMessage = CommanderVariablesService.GetProgramDisabledMessage();

            ViewBag.ProgramDisablingDate = CommanderVariablesService.GetProgramDisablingDate();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ProgramParameters(bool EnableProgram, 
            string ProgramDisabledMessage, DateTime ProgramDisablingDate)
        {
            CommanderVariablesService.ModifyCommanderVariables(EnableProgram,
                ProgramDisabledMessage, ProgramDisablingDate);
            return RedirectToAction("Index", "Home");
        }
    }
}

ProceduresRecord.Web.MVC/Views/Commander/DeleteDataBase.cshtml
@{
    ViewBag.Title = "Borrar Base de Datos";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("DeleteDataBaseConfirmed", "Commander"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        Seguro!?? Con esto borras toda la Base de Datos y no puede deshacerse...

        <br />
        <br />

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Confirmar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

ProceduresRecord.Web.MVC/Views/Commander/ProgramParameters.cshtml
@{
    ViewBag.Title = "Parámetros de Programa";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        Recuerda que si el web config tiene su variable ProgramIsAuthorized en false<br />
        el programa no funcionará independientemente de cómo esten seteados estos valores.<br />
        Por defecto, dicha variable estará en true.
        <br />
        <br />

        <div class="form-group">
            @Html.Label("Habilitar Programa", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EnableProgram",
                    (IEnumerable<SelectListItem>)ViewBag.ProgramEnabled,
                    new { @class = "selectpicker" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Mensaje de Inhabilitación", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBox("ProgramDisabledMessage", (string)ViewBag.ProgramDisabledMessage,
                    new { @class = "form-control", @type = "text" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Fecha de Inhabilitación", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*Chrome has a different behaviour for DatePickers so we have to manually set the proper date format so it's current value may be shown correctly.*@
                @if (Request.UserAgent != null && Request.UserAgent.Contains("Chrome"))
                {
                    @Html.TextBox("ProgramDisablingDate",
                        ((DateTime)ViewBag.ProgramDisablingDate).ToString("yyyy-MM-dd"),
                        new { @class = "form-control", @type = "date" })
                }
                else
                {
                    @Html.TextBox("ProgramDisablingDate",
                        (DateTime)ViewBag.ProgramDisablingDate,
                        new { @class = "form-control", @type = "date" })
                }
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Confirmar" class="btn btn-default" />
            </div>
        </div>
    </div>
}